"""Initial migration

Revision ID: 43839cc4f3ed
Revises: 
Create Date: 2023-07-28 10:40:36.696026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43839cc4f3ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diseases',
    sa.Column('Serial_Number_D', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('geneNID', sa.TEXT(), nullable=True),
    sa.Column('diseaseNID', sa.TEXT(), nullable=True),
    sa.Column('diseaseId', sa.TEXT(), nullable=True),
    sa.Column('geneId', sa.TEXT(), nullable=True),
    sa.Column('diseaseName', sa.TEXT(), nullable=True),
    sa.Column('geneName', sa.TEXT(), nullable=True),
    sa.Column('score', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('Serial_Number_D')
    )
    op.create_table('herbs',
    sa.Column('Serial_Number_H', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Compound', sa.TEXT(), nullable=True),
    sa.Column('TCMID_ID', sa.TEXT(), nullable=True),
    sa.Column('Genes', sa.TEXT(), nullable=True),
    sa.Column('GeneId', sa.TEXT(), nullable=True),
    sa.Column('herbName', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('Serial_Number_H')
    )
    op.drop_table('test_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('test_data', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('herbs')
    op.drop_table('diseases')
    # ### end Alembic commands ###
